# Generated by Django 5.0.10 on 2024-12-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="training_program",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
