# Generated by Django 5.0.10 on 2024-12-14 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_training_program"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="facial_image",
            new_name="image",
        ),
    ]
